<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vault.Services.Identity.Application\Vault.Services.Identity.Application.csproj" />
    <ProjectReference Include="..\Vault.Services.Identity.Infrastructure\Vault.Services.Identity.Infrastructure.csproj" />
  </ItemGroup>

</Project>
